### ISSUE TITLE
Call to undefined method laravel\pagseguro\Facades\PagSeguro::setReference()

### ISSUE THREAD

**Issue by andersonxss** [artistas/laravel-pagseguro#105]
Ola boa tarde!
Como consigo resolver esse problema, pois já fiz todo o procedimento da documentação e mesmo assim não consigo fazer a ligação para o método setReference().

**Comment by fernandobandeira** [comment]
Ta acontecendo isso contigo pois esta utilizando outra biblioteca no teu codgo fonte, o caminho laravel/pagseguro/Facades nao existe nesta biblioteca, ve se tu tem outra biblioteca do pagseguro no teu composer e remove a mesma do composer e do config para evitar conflitos, da pra fazer esta biblioteca trabalhar junto mas dai teria que importar os arquivos diretamente para evitar os conflitos.
