### ISSUE TITLE
Auxilio na integração

### ISSUE THREAD

**Issue by SouzaDH91** [artistas/laravel-pagseguro#116]
Primeiramente, peço desculpas se não for a forma correta pra pedir ajuda, mas se possível, teria como algum de vocês me auxiliar na integração do pagseguro? uso laravel 5.5 e preciso muito fazer essa integração, já tentei seguindo a wiki daqui e seguindo uma outra forma, mas não consegui, desculpa por isso, mas integração com api to a pouco tempo aprendendo. Ficaria muito grato se puderem me dar um auxilio

**Comment by fernandobandeira** [comment]
Eu vou fechar a issue aqui por hora, caso estiver ainda com duvidas, pode abrir uma nova issue e descrever a duvida que tiver,  normalmente o pessoal ajuda quando a duvida esta um pouco mais detalhada... Me da um ping qualquer coisa que eu respondo =P
