### ISSUE TITLE
erro 53041. installment value invalid value

### ISSUE THREAD

**Issue by infussolucoes** [artistas/laravel-pagseguro#118]
Mesmo após consultar o parcelamento via javascript, e utilizando o valor que ele me retorna, sempre da esse erro quando envio o PHP.
PagSeguroException {#395 ▼
  #message: "installment value invalid value: 50.20"
  #code: 53041
  #file: "/home1/infusc21/aguia.infus.inf.br/vendor/artistas/laravel-pagseguro/src/Artistas/PagSeguroClient.php"
  #line: 158
  -trace: {▶}
}

**Comment by henriquuepedro** [comment]
Como solucionou?
