### ISSUE TITLE
Laravel 6 Suporte

### ISSUE THREAD

**Issue by dionlopes** [artistas/laravel-pagseguro#120]
`Problem 1
    - Conclusion: remove laravel/framework v6.0.0
    - Conclusion: don't install illuminate/support v5.8.35
    - Conclusion: don't install illuminate/support v5.8.34
    - Conclusion: don't install illuminate/support v5.8.33
    - Conclusion: don't install illuminate/support v5.8.32
    - Conclusion: don't install illuminate/support v5.8.31
    - Conclusion: don't install illuminate/support v5.8.30
    - Conclusion: don't install illuminate/support v5.8.29
    - Conclusion: don't install illuminate/support v5.8.28
    - Conclusion: don't install illuminate/support v5.8.27
    - Conclusion: don't install illuminate/support v5.8.24
    - Conclusion: don't install illuminate/support v5.8.22
    - Conclusion: don't install illuminate/support v5.8.20
    - Conclusion: don't install illuminate/support v5.8.19
    - Conclusion: don't install illuminate/support v5.8.18
    - Conclusion: don't install illuminate/support v5.8.17
    - Conclusion: don't install illuminate/support v5.8.15
    - Conclusion: don't install illuminate/support v5.8.14
    - Conclusion: don't install illuminate/support v5.8.12
    - Conclusion: don't install illuminate/support v5.8.11
    - Conclusion: don't install illuminate/support v5.8.9
    - Conclusion: don't install illuminate/support v5.8.8
    - Conclusion: don't install illuminate/support v5.8.4
    - Conclusion: don't install illuminate/support v5.8.3
    - Conclusion: don't install illuminate/support v5.8.2
    - Conclusion: don't install illuminate/support v5.8.0
    - Conclusion: don't install illuminate/support v5.7.28
    - Conclusion: don't install illuminate/support v5.7.27
    - Conclusion: don't install illuminate/support v5.7.26
    - Conclusion: don't install illuminate/support v5.7.23
    - Conclusion: don't install illuminate/support v5.7.22
    - Conclusion: don't install illuminate/support v5.7.21
    - Conclusion: don't install illuminate/support v5.7.20
    - Conclusion: don't install illuminate/support 5.7.19
    - Conclusion: don't install illuminate/support 5.7.18
    - Conclusion: don't install illuminate/support 5.7.17
    - Conclusion: don't install illuminate/support v5.7.15
    - Conclusion: don't install illuminate/support v5.7.11
    - Conclusion: don't install illuminate/support v5.7.10
    - Conclusion: don't install illuminate/support v5.7.9
    - Conclusion: don't install illuminate/support v5.7.8
    - Conclusion: don't install illuminate/support v5.7.7
    - Conclusion: don't install illuminate/support v5.7.6
    - Conclusion: don't install illuminate/support v5.7.5
    - Conclusion: don't install illuminate/support v5.7.4
    - Conclusion: don't install illuminate/support v5.7.3
    - Conclusion: don't install illuminate/support v5.7.2
    - Conclusion: don't install illuminate/support v5.7.1
    - Conclusion: don't install illuminate/support v5.7.0
    - Conclusion: don't install illuminate/support v5.6.39
    - Conclusion: don't install illuminate/support v5.6.38
    - Conclusion: don't install illuminate/support v5.6.37
    - Conclusion: don't install illuminate/support v5.6.36
    - Conclusion: don't install illuminate/support v5.6.35
    - Conclusion: don't install illuminate/support v5.6.34
    - Conclusion: don't install illuminate/support v5.6.33
    - Conclusion: don't install illuminate/support v5.6.32
    - Conclusion: don't install illuminate/support v5.6.31
    - Conclusion: don't install illuminate/support v5.6.30
    - Conclusion: don't install illuminate/support v5.6.29
    - Conclusion: don't install illuminate/support v5.6.28
    - Conclusion: don't install illuminate/support v5.6.27
    - Conclusion: don't install illuminate/support v5.6.26
    - Conclusion: don't install illuminate/support v5.6.25
    - Conclusion: don't install illuminate/support v5.6.24
    - Conclusion: don't install illuminate/support v5.6.23
    - Conclusion: don't install illuminate/support v5.6.22
    - Conclusion: don't install illuminate/support v5.6.21
    - Conclusion: don't install illuminate/support v5.6.20
    - Conclusion: don't install illuminate/support v5.6.19
    - Conclusion: don't install illuminate/support v5.6.17
    - Conclusion: don't install illuminate/support v5.6.16
    - Conclusion: don't install illuminate/support v5.6.15
    - Conclusion: don't install illuminate/support v5.6.14
    - Conclusion: don't install illuminate/support v5.6.13
    - Conclusion: don't install illuminate/support v5.6.12
    - Conclusion: don't install illuminate/support v5.6.11
    - Conclusion: don't install illuminate/support v5.6.10
    - Conclusion: don't install illuminate/support v5.6.9
    - Conclusion: don't install illuminate/support v5.6.8
    - Conclusion: don't install illuminate/support v5.6.7
    - Conclusion: don't install illuminate/support v5.6.6
    - Conclusion: don't install illuminate/support v5.6.5
    - Conclusion: don't install illuminate/support v5.6.4
    - Conclusion: don't install illuminate/support v5.6.3
    - Conclusion: don't install illuminate/support v5.6.2
    - Conclusion: don't install illuminate/support v5.6.1
    - Conclusion: don't install illuminate/support v5.6.0
    - Conclusion: don't install illuminate/support v5.5.44
    - Conclusion: don't install illuminate/support v5.5.43
    - Conclusion: don't install illuminate/support v5.5.41
    - Conclusion: don't install illuminate/support v5.5.40
    - Conclusion: don't install illuminate/support v5.5.39
    - Conclusion: don't install illuminate/support v5.5.37
    - Conclusion: don't install illuminate/support v5.5.36
    - Conclusion: don't install illuminate/support v5.5.35
    - Conclusion: don't install illuminate/support v5.5.34
    - Conclusion: don't install illuminate/support v5.5.33
    - Conclusion: don't install illuminate/support v5.5.28
    - Conclusion: don't install illuminate/support v5.5.17
    - Conclusion: don't install illuminate/support v5.5.16
    - Conclusion: don't install illuminate/support v5.5.2
    - Conclusion: don't install illuminate/support v5.5.0
    - Conclusion: don't install illuminate/support v5.4.36
    - Conclusion: don't install illuminate/support v5.4.27
    - Conclusion: don't install illuminate/support v5.4.19
    - Conclusion: don't install illuminate/support v5.4.17
    - Conclusion: don't install illuminate/support v5.4.13
    - Conclusion: don't install illuminate/support v5.4.9
    - Conclusion: don't install illuminate/support v5.4.0
    - Conclusion: don't install illuminate/support v5.3.23
    - Conclusion: don't install illuminate/support v5.3.16
    - Conclusion: don't install illuminate/support v5.3.4
    - Conclusion: don't install illuminate/support v5.3.0
    - Conclusion: don't install illuminate/support v5.2.45
    - Conclusion: don't install illuminate/support v5.2.43
    - Conclusion: don't install illuminate/support v5.2.37
    - Conclusion: don't install illuminate/support v5.2.32
    - Conclusion: don't install illuminate/support v5.2.31
    - Conclusion: don't install illuminate/support v5.2.28
    - Conclusion: don't install illuminate/support v5.2.27
    - Conclusion: don't install illuminate/support v5.2.26
    - Conclusion: don't install illuminate/support v5.2.25
    - Conclusion: don't install illuminate/support v5.2.24
    - Conclusion: don't install illuminate/support v5.2.21
    - Conclusion: don't install illuminate/support v5.2.19
    - Conclusion: don't install illuminate/support v5.2.7
    - Conclusion: don't install illuminate/support v5.2.6
    - Conclusion: don't install illuminate/support v5.2.0
    - Conclusion: don't install illuminate/support v5.1.41
    - Conclusion: don't install illuminate/support v5.1.31
    - Conclusion: don't install illuminate/support v5.1.30
    - Conclusion: don't install illuminate/support v5.1.28
    - Conclusion: don't install illuminate/support v5.1.25
    - Conclusion: don't install illuminate/support v5.1.22
    - Conclusion: don't install illuminate/support v5.1.20
    - Conclusion: don't install illuminate/support v5.1.16
    - Conclusion: don't install illuminate/support v5.1.13
    - Conclusion: don't install illuminate/support v5.1.8
    - Conclusion: don't install illuminate/support v5.1.6
    - Conclusion: don't install illuminate/support v5.1.2
    - Conclusion: don't install illuminate/support v5.1.1
    - Conclusion: don't install illuminate/support v5.0.33
    - Conclusion: don't install illuminate/support v5.0.28
    - Conclusion: don't install illuminate/support v5.0.26
    - Conclusion: don't install illuminate/support v5.0.25
    - Conclusion: don't install illuminate/support v5.0.22
    - Conclusion: don't install illuminate/support v5.0.4
    - Conclusion: don't install illuminate/support v5.0.0
    - Conclusion: don't install illuminate/support 5.8.x-dev
    - Conclusion: don't install illuminate/support 5.7.x-dev
    - Conclusion: don't install illuminate/support 5.6.x-dev
    - Conclusion: don't install illuminate/support 5.5.x-dev
    - Conclusion: don't install illuminate/support 5.4.x-dev
    - Conclusion: don't install illuminate/support 5.3.x-dev
    - Installation request for artistas/laravel-pagseguro ^1.7 -> satisfiable by artistas/laravel-pagseguro[v1.7.0].
    - Conclusion: don't install illuminate/support 5.2.x-dev
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework v6.0.0
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework v6.0.0
    - artistas/laravel-pagseguro v1.7.0 requires illuminate/support 5.* -> satisfiable by illuminate/support[5.0.x-dev, 5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - Conclusion: don't install illuminate/support 5.1.x-dev
    - Installation request for laravel/framework 6.0 -> satisfiable by laravel/framework[v6.0.0].`

**Comment by fernandobandeira** [comment]
Acabei de lancar a versao 1.8.0, foi adicionado o suporte para o L6 nela. Me da um ping caso nao estiver 100%.
