### ISSUE TITLE
Alguem tem algum exemplo?

### ISSUE THREAD

**Issue by CaioMax** [artistas/laravel-pagseguro#127]
Alguém teria algum exemplo de como fazer a implementação do javascript, estou criando uma api, e preciso fazer o checkout trasnparente com os dados enviados por uma request. No caso eu criaria um controller e colocaria o script no final do controler? Se alguém pode me ajudar agradeço.

**Comment by marceloaugustocwb** [comment]
Você tem que adicionar esse script no front, o seu front que tem que te mandar esse hash, não tem como você faz isso no back é uma normal de segurança para a sua a aplicação e é um padrão do PagSeguro.
