### ISSUE TITLE
Problema na compra com cartão de crédito (cancellationSource=INTERNAL)

### ISSUE THREAD

**Issue by henriquuepedro** [artistas/laravel-pagseguro#140]
Dentro do meu sistema, trabalho com duas formas de pagamento, boleto e cartão de crédito.

Com a forma boleto, funciona normal, sem nenhum problema, já com o cartão de crédito, todos os meus clientes estão reclamando que a compra está sendo cancelada. A compra é enviada ao pagseguro, mas em seguida eles enviam uma notificação informando que a compra foi cancelada e informam apenas **cancellationSource=INTERNAL** e **status=7**.

Alguém já passou por isso? Não sei dizer se pode ser algo no código ou configuração da conta.

Agradeço desde já.

**Comment by Henriquuepedro** [comment]
{
   "date":"2020-06-04T00:14:58.000-03:00",
   "code":"656075B9-0B82-4FF8-BB19-FE75E08D9498",
   "reference":"15",
   "type":"1",
   "status":"7",
   "cancellationSource":"INTERNAL",
   "lastEventDate":"2020-06-04T00:15:01.000-03:00",
   "paymentMethod":{
      "type":"1",
      "code":"101"
   },
   "grossAmount":"134.99",
   "discountAmount":"0.00",
   "creditorFees":{
      "installmentFeeAmount":"0.00",
      "intermediationRateAmount":"0.00",
      "intermediationFeeAmount":"5.39"
   },
   "netAmount":"129.60",
   "extraAmount":"0.00",
   "installmentCount":"2",
   "itemCount":"1",
   "items":{
      "item":{
         "id":"6",
         "description":"**REMOVI POR SEGURANÇA**",
         "quantity":"1",
         "amount":"99.99"
      }
   },
   "sender":{
      "name":"**REMOVI POR SEGURANÇA**",
      "email":"**REMOVI POR SEGURANÇA**",
      "phone":{
         "areaCode":"**REMOVI POR SEGURANÇA**",
         "number":"**REMOVI POR SEGURANÇA**"
      }
   },
   "shipping":{
      "address":{
         "street":"**REMOVI POR SEGURANÇA**",
         "number":"S\/n",
         "complement":"**REMOVI POR SEGURANÇA**",
         "district":"**REMOVI POR SEGURANÇA**",
         "city":"**REMOVI POR SEGURANÇA**",
         "state":"**REMOVI POR SEGURANÇA**",
         "country":"BRA",
         "postalCode":"**REMOVI POR SEGURANÇA**"
      },
      "type":"1",
      "cost":"35.00"
   },
   "primaryReceiver":{
      "publicKey":"PUB01B4E196294D4939B3AA848227EF4612"
   }
}

**Comment by henriquuepedro** [comment]
Irei fechar pois achei a solução e vou compartilhar caso alguém passe por isso.

Entrei em contato com a PagSeguro e todos os pagamentos estavam sendo reprovados pelo sistema de segurança deles.

**O que ocorreu a final?** 
Como uso o checkout transparente, meu cliente não precisaria saber que estaria pagamento pelo PagSeguro, essa é a ideia do checkout transparente, enfim, falando com o suporte da PagSeguro eles me informaram que os pagamentos estavam sendo cancelados pelo motivo do cliente não ter um vínculo com o PagSeguro, ou seja, como a PagSeguro não encontrou uma conta vinculada ao e-mail enviado na API, o sistema de segurança cancelou a venda.

**Simplificando:** Para usar checkout transparente com cartão de crédito será necessário o cliente ter uma conta no PagSeguro.

**Comment by ivent** [comment]
Olá @Henriquuepedro estou passando pelo mesmo problema, fiz uma integração com a api de pagamento recorrente do pagseguro fiz todos os testes em modo sandbox e depois em produção e deu tudo certo ai no dia do lançamento das assinaturas nos conseguimos converter 15 assinaturas com sucesso e depois disso o pagseguro começou a cencelar todas as outras foram mais de 50 canceladas imagine o prejuízo e ter que entrar em contato com estes clientes, infelizmente "por segurança" o pagseguro não informa qual motivo do cancelamento interno e o cliente fica de mãos atadas, mas eu acredito que seja por conta de algum dado que esteja faltando no seu checkout que tenha ocultaado ou colocado como padrão,  este relato que vc fez ai é inimaginavel como eles podem obrigar alguém a ter uma conta do pag pra fazer um pagamento, mas em fim infelizmente eu vou ter que mudar de banco pois o suporte deles a anos é uma m3rda, e o suporte aos devs é um L1xo...
