### ISSUE TITLE
Não consigo usar o composer require no laravel 8

### ISSUE THREAD

**Issue by rs-benatti** [artistas/laravel-pagseguro#148]
Meu composer.json:

"php": "^7.3",
        "doctrine/dbal": "^2.11",
        "erusev/parsedown": "^1.7",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.0",
        "illuminate/support": "^8.6",
        "laravel/jetstream": "^1.3",
        "laravel/sanctum": "^2.6",
        "laravel/tinker": "^2.0",
        "livewire/livewire": "^2.0",
        "smalot/pdfparser": "^0.17.0",
        "spatie/laravel-permission": "^3.17",
        "spatie/pdf-to-text": "^1.3"

Quando uso o comando: composer require artistas/laravel-pagseguro, recebo: 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for artistas/laravel-pagseguro ^1.9 -> satisfiable by artistas/laravel-pagseguro[v1.9.0].
    - Conclusion: remove laravel/framework v8.14.0
    - Conclusion: don't install laravel/framework v8.14.0
    - artistas/laravel-pagseguro v1.9.0 requires illuminate/support ^5.2|^6.0|^7.0 -> satisfiable by illuminate/support[5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev, 6.x-dev, 7.x-dev].
    - don't install illuminate/support 5.5.x-dev|don't install laravel/framework v8.14.0
    - don't install illuminate/support 5.6.x-dev|don't install laravel/framework v8.14.0
    - don't install illuminate/support 5.7.x-dev|don't install laravel/framework v8.14.0
    - don't install illuminate/support 5.8.x-dev|don't install laravel/framework v8.14.0
    - don't install illuminate/support 6.x-dev|don't install laravel/framework v8.14.0
    - don't install illuminate/support 7.x-dev|don't install laravel/framework v8.14.0
    - don't install illuminate/support 5.2.x-dev|don't install laravel/framework v8.14.0
    - don't install illuminate/support 5.3.x-dev|don't install laravel/framework v8.14.0
    - don't install illuminate/support 5.4.x-dev|don't install laravel/framework v8.14.0
    - Installation request for laravel/framework (locked at v8.14.0, required as ^8.0) -> satisfiable by laravel/framework[v8.14.0]. 
upgrade. See https://getcomposer.org/2
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for artistas/laravel-pagseguro ^1.9 -> satisfiable by artistas/laravel-pagseguro[v1.9.0].
    - Conclusion: remove laravel/framework v8.14.0
    - Conclusion: don't install laravel/framework v8.14.0
    - artistas/laravel-pagseguro v1.9.0 requires illuminate/support ^5.2|^6.0|^7.0 -> satisfiable by illuminate/support[5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev, 6.x-dev, 7.x-dev].
    - don't install illuminate/support 5.5.x-dev|don't install laravel/framework v8.14.0
    - don't install illuminate/support 5.6.x-dev|don't install laravel/framework v8.14.0
    - don't install illuminate/support 5.7.x-dev|don't install laravel/framework v8.14.0
    - don't install illuminate/support 5.8.x-dev|don't install laravel/framework v8.14.0
    - don't install illuminate/support 6.x-dev|don't install laravel/framework v8.14.0
    - don't install illuminate/support 7.x-dev|don't install laravel/framework v8.14.0
    - don't install illuminate/support 5.2.x-dev|don't install laravel/framework v8.14.0
    - don't install illuminate/support 5.3.x-dev|don't install laravel/framework v8.14.0
    - don't install illuminate/support 5.4.x-dev|don't install laravel/framework v8.14.0
    - Installation request for laravel/framework (locked at v8.14.0, required as ^8.0) -> satisfiable by laravel/framework[v8.14.0]. 

Installation failed, reverting ./composer.json to its original content.

Aparentemente não é compatível com o Laravel 8. Mas há alguma forma de eu usar o framework sem instalar pelo composer pra tentar burlar essa incompatibilidade?

**Comment by allanbarbosa** [comment]
Já tem um pull request para atender essa instalação, precisamos de @fernandobandeira  ou @giovannipds aceitarem lá.

**Comment by casimirorocha** [comment]
Mesmo problema aqui!

**Comment by lucasgiovanny** [comment]
Caso queiram contornar o problema temporariamente, uma vez que o PR com suporte ao Laravel 8 ainda não foi aprovado, editem o `composer.json` para utilizar o repositório com o fix.

Adicionar isto:

```json
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/lucasgiovanny/laravel-pagseguro"
        }
    ],
```

Alterar isto:
```json
"artistas/laravel-pagseguro": "dev-master",
```

Executar:
```bash
composer update
```

Quando o PR for aprovado com o suporte ao Laravel 8, é só remover o repositório personalizado do ```composer.json```.

**Comment by giovannipds** [comment]
> Já tem um pull request para atender essa instalação, precisamos de @fernandobandeira ou @giovannipds aceitarem lá.

Atualmente não tenho acesso de escrita nem sou mantenedor da biblioteca, o @fernandobandeira é que cuidava dela.

**Comment by fernandobandeira** [comment]
Acabei de aprovar o PR, lancei a versao 1.10.0, daqui pra frente a lib ja vai aceitar qualquer versao do laravel, estou procurando novos maintainers para o projeto, se estiverem interessados deem uma olhada na issue #152
