### ISSUE TITLE
Incompatibilidade com o laravel 8

### ISSUE THREAD

**Issue by Lsantos-art** [artistas/laravel-pagseguro#150]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires artistas/laravel-pagseguro ^1.9 -> satisfiable by artistas/laravel-pagseguro[v1.9.0].
    - artistas/laravel-pagseguro v1.9.0 requires illuminate/support ^5.2|^6.0|^7.0 -> found illuminate/support[v5.2.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by fernandobandeira** [comment]
Acabei de aprovar o PR, lancei a versao 1.10.0, daqui pra frente a lib ja vai aceitar qualquer versao do laravel, estou procurando novos maintainers para o projeto, se estiverem interessados deem uma olhada na issue #152
