### ISSUE TITLE
Link de retorno não está funcionando 

### ISSUE THREAD

**Issue by guiireal** [artistas/laravel-pagseguro#163]
Pessoal bom dia!

Fiz um teste mudando de sandbox pra produção, porém quando vou consultar a transação o webhook de retorno não tem nada a ver com o que está cadastrado no meu sistema e não consigo receber os retornos

![image](https://github.com/artistas/laravel-pagseguro/assets/13739343/744485d0-d99e-4ea1-9a56-e93d4a6e6723)

**Comment by guiireal** [comment]
Pelo que constatei, o Pag Seguro implementou uma camada extra de segurança nos links.
Eles agora validam se os webhooks implementam HTTPS, se o certificado é válido, etc.

Atualizei o certificado digital do servidor do webhook e voltou a funcionar!

**Comment by gustavocoimbradev** [comment]
@guiireal sabe se tem como desativar isso de alguma forma?

**Comment by gustavocoimbraold** [comment]
@guiireal sabe se tem como desativar isso de alguma forma?

Edit: Acabei de testar com https.. deu o mesmo erro :(

![image](https://github.com/artistas/laravel-pagseguro/assets/115879524/e4ae8e90-7e45-42af-90f3-33aba9935660)

**Comment by guiireal** [comment]
> @guiireal sabe se tem como desativar isso de alguma forma?
> 
> Edit: Acabei de testar com https.. deu o mesmo erro :(
> 
> ![image](https://private-user-images.githubusercontent.com/115879524/325958353-e4ae8e90-7e45-42af-90f3-33aba9935660.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNjIyMjUsIm5iZiI6MTcxNDE2MTkyNSwicGF0aCI6Ii8xMTU4Nzk1MjQvMzI1OTU4MzUzLWU0YWU4ZTkwLTdlNDUtNDJhZi05MGYzLTMzYWJhOTkzNTY2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQyMDA1MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2MzNGJjZDUyYzhjODFlOWM2NDFkZDE2NWZhN2JhYWYzOWU3NDVmYjVjNjYzYTZhZjZhMTA5ZGFlYTMyMDE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kyxW-4qTTfoTVoQMortAIdh9V9ci1z01MQPuYmGu_Y8)

Mano, aqui não chegou a dar erro 500, os que davam era na própria pag seguro.
Nos seus logs ele não pega nenhum erro do teu lado?
