### ISSUE TITLE
Pagamento recorrente

### ISSUE THREAD

**Issue by rrfaria** [artistas/laravel-pagseguro#18]
Poderia implantar a função de pagamento recorrente no projeto ... ta ficando bom isso aqui ...

**Comment by fernandobandeira** [comment]
Guia da implementação:

http://download.uol.com.br/pagseguro/docs/pagamento-recorrente-transparente.pdf

Será preciso reestruturar a package dividindo melhor as classes para implementar esta forma de pagamento. Vou deixar esta feature para ser implementada depois de estabilizar o checkout transparente normal, depois da versão 1.0.0

**Comment by leommsilva** [comment]
Olá, já tem uma previsão para habilitar o pagamento recorrente ? ou já está habilitado ? melhor pack do pagseguro!

**Comment by fernandobandeira** [comment]
Olá, esta em desenvolvimento, já tem uma versão com o pagamento recorrente funcionando, mas estou fazendo alguns testes e ajustes finais antes de liberar para todos, espero lançar uma versão até o final da semana que vem (03/02) 😄

**Comment by diego-goulart** [comment]
Aguardando anciosamente :+1:

**Comment by fernandobandeira** [comment]
Lançada versão 1.2.0, 

Ela já possibilita fazer pagamentos recorrentes, não tem todos os métodos da api, mas já é possível fazer um sistema de assinaturas pois os essenciais já estão implementados...

**Comment by operfildoluiz** [comment]
Tem algum demo? Estou me batendo pra implementar o pagamento recorrente com o guia da Wiki.

**Comment by fernandobandeira** [comment]
Me add no skype fernando.bandeira@outlook.com , me explica lá que eu te ajudo, acho que fica mais facil...

**Comment by brunorbarroso** [comment]
Fala, @fernandobandeira. Você tem alguma previsão para liberar uma atualização com o pagamento recorrente? ou então, como utiliza-lo usando o seu pacote?

Obrigado! ^^

**Comment by fernandobandeira** [comment]
@brunorbarroso na versão 1.2.1 eu liberei algumas funcionalidades, da uma olhada na wiki:
https://github.com/artistas/laravel-pagseguro/wiki/3.1.-Cria%C3%A7%C3%A3o-de-um-Plano

Tem algumas coisas que estão pendentes mas o básico do pagamento recorrente já está funcionando, o que está na wiki está finalizado ao menos 😄...

**Comment by ivanrufino** [comment]
Não estou conseguindo criar um formulario para enviar o senderHash, alguem poderia me ajuda

**Comment by brunorbarroso** [comment]
Valeu pelo feedback, @fernandobandeira. Só vi hoje quando recebi a notificação do @ivanrufino.
