### ISSUE TITLE
Erro em PagSeguro::getSession(): Serialization of 'SimpleXMLElement

### ISSUE THREAD

**Issue by novasky-zz** [artistas/laravel-pagseguro#20]
Estou tentando implementar o pacote em meu formulário próprio.
Contudo, estou recebendo a mensagem "Serialization of 'SimpleXMLElement' is not allowed".

Dando uma rápida olhada, percebi algo que possivelmente estava gerando o meu problema:
Artistas/PagSeguroClient.php na linha 75:

> $this->session->put('pagseguro.session', $result->id);

Contudo, o $result->id não é uma string. O retorno dela é:

> SimpleXMLElement {#362 ▼
>   +0: "id-retornado"
> }

Isso gera a mensagem "Serialization of 'SimpleXMLElement' is not allowed" ao tentar armazenar esse valor na Sessão. Se eu forçar o retorno da string da seguinte maneira, o retorno seria uma string que possibilitaria a serialização:

> $this->session->put('pagseguro.session', (string) $result->id);

O retorno:

> "id-retornado"

Estou correto, ou eu que estou implementando isso erroneamente?

Agradeço desde já. Abraço.

**Comment by fernandobandeira** [comment]
Olá, vou dar uma olhada amanhã, e qualquer coisa já ajusto na lib e lanço uma nova versão, a princípio o retorno deveria ser uma string.

**Comment by fernandobandeira** [comment]
Realizei os casts no SimpleXML e lancei uma nova versão, 0.4.2, dependendo da versão do PHP ele já faz o cast automático disso por isso aqui ele não estava dando o erro mas em outro ambiente consegui reproduzir.

Você pode dar um GET na rota `/pagseguro/session` para conseguir o hash da sessão também, se estiver usando algo tipo vuejs ou angular pode acabar sendo útil.
