### ISSUE TITLE
Pagseguro Sandbox: Service Temporarily Unavailable

### ISSUE THREAD

**Issue by novasky-zz** [artistas/laravel-pagseguro#30]
Deparei-me com esta tela de manutenção do Pagseguro Sandbox http://prntscr.com/cw8sta

Sendo assim, eu não consigo realizar transações na minha implementação, rebendo o erro:

> ErrorException in PagSeguroClient.php line 66:
> simplexml_load_string(): Entity: line 1: parser error : Space required after the Public Identifier

Identifiquei o seguinte. Na classe PagSeguroClient.php, método sendTransaction() na linha que é executado o CURL:

> $result = curl_exec($ch);

Se eu utilizar um echo $result me retorna o seguinte: http://prntscr.com/cw8uqf
Ou seja, ocasiona um erro 503 do servidor. O que não entra em nenhuma condição de tratamento que vem logo abaixo desse trecho do código.

Como sugestão, poderia ser utilizado após o curl_exec o seguinte:

> $getInfo = curl_getinfo($ch);

Esse cara retornaria o seguinte: http://prntscr.com/cw8vxy
Com esse array, poderia ser tratado chamando o índice 'http_code' e verificando se o mesmo retorno uma resposta válida do servidor.

Dessa forma, seria melhor para eu tratar o sistema de pagamento informando ao usuário que o serviço está temporariamente indisponível.

Espero que eu tenha sido claro na minha explicação.
Se eu estiver realizando alguma coisa errada, por favor me informe.

Fico no aguardo. Abraço.

**Comment by fernandobandeira** [comment]
Ajustei e lancei a versão 0.5.2, coloquei um código único pra cada exceção para conseguir distinguir elas.
