### ISSUE TITLE
Resposta com link do boleto.

### ISSUE THREAD

**Issue by vanessasoutoc** [artistas/laravel-pagseguro#36]
Apesar de muitos erros de validação, comentei algumas linhas e os dados são enviados para o sandbox. 
Entretanto, não retorna dados de resposta do sandbox. 
Alguém sabe me dizer o que pode ser!??

**Comment by compil3r** [comment]
Estou com o mesmo problema. Como recuperar o link de debito e de boleto?

**Comment by fernandobandeira** [comment]
O sandbox não retorna nada? Tenta verificar se o servidor está conseguindo fazer requisições externas, o sandbox retorna algo sempre, mesmo que tudo que tu passe pra ele esteja errado, incluindo as credenciais...

**Comment by vanessasoutoc** [comment]
@fernandobandeira Acontece que o retorno esta em xml, ai quando tento ver a resposta no log não aparece nada... resolvi utilizando a seguinte verificação 
if($pagseguro->stauts){
....
}

**Comment by fernandobandeira** [comment]
AH blz, eu não documentei o retorno, acho que daria pra colocar uns exemplos na wiki, vou deixar aberta a issue pra me lembrar de fazer isso nos proximos dias...
