### ISSUE TITLE
Erro ao gerar adesão ao pagamento recorrente

### ISSUE THREAD

**Issue by charleskx** [artistas/laravel-pagseguro#48]
Sempre que tento aderir ao pagamento recorrente, ele me retorna o seguinte erro:
PagSeguroException in PagSeguroClient.php line 173:
Method of payment currently unavailable.

**Comment by rogerio-pereira** [comment]
@charleskx conseguiu resolver? O meu estava dando erro, mas funcionou de uma hora para outra, não sei o que fiz

**Comment by charleskx** [comment]
Consegui resolver sim, só não lembro o que fiz agora kkk
Ainda tá com problema?

**Comment by fernandobandeira** [comment]
Fechado por enquanto ja que nao conseguimos mais reproduzir a issue.
