### ISSUE TITLE
Adição de opcionalidade de endereço de entrega.

### ISSUE THREAD

**Issue by Dalponte-zz** [artistas/laravel-pagseguro#49]
Adicionando a seguinte configuração como parâmetro `'shippingAddressRequired' => 'false'` faz com que não seja necessário enviar dados de entrega (`shippingInfo`  e `shippingAddress`) para casos em que não há produtos a serem enviados.

**Comment by Luizgpp** [comment]
Ola, Obrigado pela Library.
Como não foi implementado ainda. Tem alguma forma de eu inserir essa opção manualmente? Podem me ajudar? Obrigado

**Comment by fernandobandeira** [comment]
Eu alterei isso na nova versão (método é opcional agora, se não chamar ele passa esse parametro), mas pelo que eu vi no caso de cartão de crédito ainda vai ter que informar o endereço de cobrança, o pagseguro continua exigindo, tentei enviar um ``` 'billingAddressRequired' => 'false' ``` mas ele não aceita...

E no recorrente também não achei uma forma de desativar, procurei na doc também e não tem, lembrando que a do recorrente tem outra sintaxe e só aceita cartão...

Se alguém tiver algum problema ou encontrar novas informações comenta que eu reabro a issue.
