### ISSUE TITLE
Onde eu encontro os bancos aceitos para o Débito Online ?

### ISSUE THREAD

**Issue by SkillDeeSouza** [artistas/laravel-pagseguro#50]
Estou tentando encontrar na documentação os nome dos bancos aceitos para o Débito Online.
No exemplo da sua biblioteca tem `itau `como exemplo.

Como são chamados os outros ?

Obrigado!

**Comment by fernandobandeira** [comment]
Formato: bradesco, itau, bancodobrasil, banrisul ou hsbc

Mais informações:
http://download.uol.com.br/pagseguro/docs/pagseguro-checkout-transparente.pdf

No caso o HSBC não existe mais.

**Comment by SkillDeeSouza** [comment]
Eita! Não conseguia encontrar de jeito nenhum. Li e reli várias vezes! Mas por causa do formato da documentação não conseguia encontrar. Obrigado!
