### ISSUE TITLE
Erro ao efetuar pagamento em produção

### ISSUE THREAD

**Issue by DotAmzi** [artistas/laravel-pagseguro#51]
Em sandbox o pagamento e realizado perfeitamente.
Em produção ele não é realizado e não retorna nenhuma mensagem de erro.
Somente o status 301.
Esse erro ocorre somente para checkout transparente.

**Comment by icarojobs** [comment]
Testamos na versão 1.4.0 e está OK!

Já tentou dar comandos de cache e clear?

$ php artisan config:clear
$ php artisan config:cache

OBS: Verifique também seu PAGSEGURO_TOKEN, pois o token de produção é diferente do de sandbox.

**Comment by DotAmzi** [comment]
Achei a solução do problema, tratava-se de um problemas com rotas. Já foi solucionado, nada com a library em questão. Valeu @icarojobs
