### ISSUE TITLE
Suporte às notificações das Assinaturas

### ISSUE THREAD

**Issue by cassianogf** [artistas/laravel-pagseguro#52]
Agora o PagSeguro tem outro modelo de notificação que tem como o parâmetro o ` notificationType => 'preApproval'` e essas notificações podem ser consultadas usando o link `https://ws.pagseguro.uol.com.br/v2/pre-approvals/notifications/{notificationCode}` 

Ao usar o `PagSeguroRecorrente::notification($notificationCode) `ele busca diretamente nas transações e não nas assinaturas, retornando assim como Not Found

**Comment by fernandobandeira** [comment]
Adicionado com o PR #53, Versão 1.2.2
