### ISSUE TITLE
Unauthorized: Não foi possível estabelecer uma conexão com o PagSeguro.

### ISSUE THREAD

**Issue by gbvacco** [artistas/laravel-pagseguro#59]
Olá, 

Estava utilizando normalmente o pagseguro, mas ontem ao dar um update no composer recebi uma atualização e desde então estou recebendo a seguinte mensagem "Unauthorized: Não foi possível estabelecer uma conexão com o PagSeguro." ... 

Fiz outras modificações também e tenho tentado verificar o que aconteceu, já verifiquei o token e as configurações, mas até o momento sem sucesso ...

**Comment by fernandobandeira** [comment]
Olá, da uma olhada nesta página:
https://github.com/artistas/laravel-pagseguro/wiki/6.-Migra%C3%A7%C3%A3o

Teoricamente pelo composer você não deveria receber este update para o 1.4, tente rodar o comando:

```
php artisan vendor:publish --tag=config
```

Ele vai publicar um arquivo de configuração na pasta config, depois me diz se o erro persiste. 👍 

**Edit:**

Para evitar que ocorra algo assim no futuro, troca o que estiver no seu composer.json por:

```
"artistas/laravel-pagseguro": "1.4.*"
```

Já atualizei a Wiki...

**Comment by gbvacco** [comment]
No meu composer.json estava da seguinte maneira 
`"artistas/laravel-pagseguro": "^1.2",`
Rodei o comando recomendado mas só com isso o problema persistiu, então atualizei no composer.json para 
`"artistas/laravel-pagseguro": "1.4.*"`
E rodei o update 
Depois refiz os passos de instalação do tópico 1 da instalação e agora está rodando normalmente.

@fernandobandeira Agradeço pela ajuda e pelo package 😃
