### ISSUE TITLE
Unauthorized: Não foi possível estabelecer uma conexão com o PagSeguro

### ISSUE THREAD

**Issue by igorpdasilvaa** [artistas/laravel-pagseguro#61]
Olá, talvez esse problema que estou enfrentando seja por causa de falta de conhecimento não neccessáriamente um bug no sistema de vcs, enfim segue a baixo o problema.

erro:
```
Unauthorized: Não foi possível estabelecer uma conexão com o PagSeguro.
--
in PagSeguroClient.php (line 139)
```
meu código: 
```
......
......
.....
<script type="text/javascript" src="/pagseguro/javascript"></script>
        <script>
            PagSeguroDirectPayment.setSessionId('{{ PagSeguro::startSession() }}'); 
        </script>
......
......
......
```
minha configuração .env (email e token ficticios porem acredito estar usando os dados corretos rsrs)
```

#pagseguro settings
PAGSEGURO_SANDBOX=true
PAGSEGURO_EMAIL=email@gmail.com
PAGSEGURO_TOKEN=135772AD6B3C401ABC7EE285FC0G972A
PAGSEGURO_NOTIFICATION=/payment/notification

```
Basicamente o que fiz ate agora foi seguir os passos 1 e 1.1 da wiki. espero que alguem consiga me ajudar ou caso seja algum problema no sistema eu consiga ser util para ajudar a soluciona-lo.

informações de ambiente utilizado:

php: 7.1.7
laravel: 5.4

Dês de já agradeço pela atenção.

**Comment by igorpdasilvaa** [comment]
tava vendo aqui, o problema é que não ta conseguindo pegar meu e-mail e token do .env ai ta dando esse pau, eu fiz uma gambiarra aqui pra ir funcionando mas tem que ver ao certo o motivo disso e se só está accontecendo comigo.

**Comment by robertotcestari** [comment]
Igor, tente dar o comando php artisan config:cache

Em Sex, 4 de ago de 2017 15:27, igorpdasilvaa <notifications@github.com>
escreveu:

**Comment by igorpdasilvaa** [comment]
cache limpo porem problema continua igual :(

**Comment by robertotcestari** [comment]
Verifique se o token utilizado é o do sandbox, pois ele é diferente do
token da produção. Você pode também verificar quais variáveis seu app está
puxando do .env usando o tinker. Dá uma olhada se retorna o token correto.

Abs

Em Sex, 4 de ago de 2017 17:16, igorpdasilvaa <notifications@github.com>
escreveu:

**Comment by igorpdasilvaa** [comment]
o token está correto, como disse fiz uma gambiarrinha aqui pra funcionar, sobre o tinker irei verificar dps mas o problema está nas variaveis do .env msm. só não estou com muito tempo para verificar isso por causa do projeto que tenho que entregar. depois quando eu tiver com mais tempo posto qual foi a gambiarra q fiz e também o que tive que modificar para funcionar 100%.  

Abs e vlw pela ajuda !!

**Comment by 4nd114** [comment]
estou com o mesmo problema se possível encaminhar a solução, agradeço dese já.

**Comment by fernandobandeira** [comment]
Acredito que isto tenha sido causado por algum problema no arquivo de config (talvez ele não foi publicado ou algo assim), agora eu coloquei pra ele pegar do env caso o config não esteja publicado então possivelmente este erro não vai mais ocorrer, se tiverem problemas na nova versão comenta que eu reabro a issue.

**Comment by gabriel89oliveira** [comment]
Eu estava com esse mesmo problema, e com os comandos abaixo voltou a funcionar.
```
php artisan route:cache
php artisan config:cache
```

Deve ser algum problema para o Laravel reconhecer as variáveis do arquivo .env quando o mesmo é alterado.
Espero que essa dica ajude.

**Comment by casimirorocha** [comment]
Amigo eu estava com esse mesmo problema, porém o token que eu estava informando era o token de PRODUÇÃO, você deve informar o token de SANDBOX caso esteja fazendo testes, você consegue o token aqui: https://sandbox.pagseguro.uol.com.br/vendedor/configuracoes.html depois de inserir o token tem que todar o php artisan config:clear só assim irá funcionar, abraços.

**Comment by DiogoAJC** [comment]
Resolvi este problema com 

`php artisan vendor:publish`
