### ISSUE TITLE
Utilizar no Lumen

### ISSUE THREAD

**Issue by allanzi** [artistas/laravel-pagseguro#74]
Olá,
gostaria de saber se é possível utilizar no Lumen.

Abs.,

**Comment by fernandobandeira** [comment]
Nāo cheguei a utilizar com o Lumen mas ela deve estar compatível. Ela utiliza apenas o Log e Validation que sāo funcionalidades que existem no Lumen também então nāo deve haver problema.

**Comment by allanzi** [comment]
Então eu testei por cima e no boot do provider vc chama dois métodos que
não existem, eu fiz um if usando a função method_exists e não deu mais
erro, mas não cheguei a testar as API

Em 23 de out de 2017 18:51, "Fernando Henrique Bandeira" <
notifications@github.com> escreveu:

**Comment by fernandobandeira** [comment]
Ok, acho que já consegui ver quais sāo os dois problemas, vou dar uma olhada nisso e em algumas outras issues e lanço uma versão essa semana...

O method_exists vai resolver estes erros mas dentro do PagSeguroConfig tem que trocar para ele usar do env quando que a config nao existe visto que no lumen nao da pra publicar o arquivo...

**Comment by fernandobandeira** [comment]
Está funcionando na nova versão, testei com o Lumen.
