### ISSUE TITLE
Desconto no próximo pagamento recorrente

### ISSUE THREAD

**Issue by murilobd** [artistas/laravel-pagseguro#79]
Procurei na API mas não encontrei um método de adicionar desconto no próximo pagamento recorrente.
Se eu fizer esse método, posso fazer um pull request para implementar na API?

Segue documentação do pagseguro: https://dev.pagseguro.uol.com.br/referencia-da-api/api-de-pagamentos-pagseguro#!/ws_pagseguro_uol_com_br/pre_approvals_discount_xml

**Comment by fernandobandeira** [comment]
Sim, se voce adicionar pode mandar um PR que eu dou merge...

**Comment by murilobd** [comment]
Feito: https://github.com/artistas/laravel-pagseguro/pull/80
