### ISSUE TITLE
Retorno do Boleto Bancário

### ISSUE THREAD

**Issue by isabellaslv** [artistas/laravel-pagseguro#84]
Quando eu envio o pagamento por boleto bancário, o pagseguro retorna um xml com o link para imprimir o boleto. Tem alguma função pronta para receber este retorno? Não encontrei na Wiki...

Obrigada!

**Comment by fernandobandeira** [comment]
Atualizei a wiki do boleto e do débito online, na chamada do ``` send ``` ele retorna o XML, dai tu pode utilizar o atributo:

```
$pagseguro->paymentLink
```

E redirecionar para a impressão do boleto.

**Comment by isabellaslv** [comment]
Obrigada! Só um detalhe, esse atributo retorna um array, então para dar redirect no link fiz assim:
```
$link = $pagseguro->paymentLink;

return redirect($link[0]);
```
