### ISSUE TITLE
Erro ao tentar resgatar Transaction code, Reference e Payment Link

### ISSUE THREAD

**Issue by byeloff** [artistas/laravel-pagseguro#85]
Olá, tudo bem? 

Estou com um problema após o método send, recebo o erro abaixo: 

-- 
Undefined property: Artistas\PagSeguro\PagSeguro::$paymentLink
--
 
`
   $pagseguro = PagSeguro::setReference($pedido->id)
      ->setSenderInfo([
        'senderName' => $input['nome'], //Deve conter nome e sobrenome
        'senderPhone' => $input['telefone'], //Código de área enviado junto com o telefone
        'senderEmail' => $cadastro->email,
        'senderHash' => $input['hash_pagseguro'],
        'senderCPF' => $input['cpf'] //Ou CNPJ se for Pessoa Júridica
      ])
      ->setShippingAddress([ // OPCIONAL
        'shippingAddressStreet' => $input['rua'],
        'shippingAddressNumber' => $input['numero'],
        'shippingAddressDistrict' => $input['bairro'],
        'shippingAddressPostalCode' => $input['cep'],
        'shippingAddressCity' => $input['cidade'],
        'shippingAddressState' => $input['estado']
      ])->setItems($carrinho);

   if($input['metodo'] == 2){

        // Boleto
        $pagseguro->send([
          'paymentMethod' => 'boleto'
        ]);

        $pedido->boleto = $pagseguro->paymentLink;
        $pedido->save();

   }
`

Alguém pode me ajudar?

**Comment by fernandobandeira** [comment]
Desculpa não ter visto antes. a issue, tem um erro no seu código:

```php
$pagseguro->send([
    'paymentMethod' => 'boleto'
]);

$pedido->boleto = $pagseguro->paymentLink;
```

Note que não está atribuindo o retorno do ``` send ``` para nenhuma variável.
