### ISSUE TITLE
Checkout

### ISSUE THREAD

**Issue by filipemacedo** [artistas/laravel-pagseguro#87]
Existiria algum comando para gerar o checkout?

**Comment by fernandobandeira** [comment]
Dá uma olhada na [wiki](https://github.com/artistas/laravel-pagseguro/wiki), lá tem toda a documentação de como deve ser feito o lado do PHP.

Se estiver se referindo ao front, caso esteja com dúvidas, pode consultar uma implementação antiga que eu havia feito:

https://github.com/artistas/laravel-pagseguro/tree/ff06237a10e4b0f8678d3544429564c2a8cf3b9d/src/Artistas/views/custom

Retirei a mesma da lib logo no início pois vi que não estava sendo muito utilizado e é algo que varia muito de projeto a projeto...
