### ISSUE TITLE
Campo reference no method para criação de Plano ausente

### ISSUE THREAD

**Issue by felipemarques** [artistas/laravel-pagseguro#89]
Boa noite,

Não encontrei nenhum padrão para abertura de issues ou pull request. Então colocarei aqui o que fiz pra poder usar o campo reference, disponivel na API do Pagseguro Recorrente.

no arquivo: ./vendor/artistas/laravel-pagseguro/src/Artistas/PagSeguroRecorrente.php
na linha 70, temo o metodo sendPreApprovalRequest com a seguinte implementacao:

    /**
     * Define os dados do plano.
     *
     * @param array $preApprovalRequest
     *
     * @return \SimpleXMLElement
     */
    public function sendPreApprovalRequest(array $preApprovalRequest)
    {
        $preApprovalRequest = [
            'email'                             => $this->email,
            'token'                             => $this->token,
            'preApprovalName'                   => $this->sanitize($preApprovalRequest, 'preApprovalName'),
            'preApprovalCharge'                 => $this->sanitize($preApprovalRequest, 'preApprovalCharge'),
            'preApprovalPeriod'                 => $this->sanitize($preApprovalRequest, 'preApprovalPeriod'),
            'preApprovalCancelUrl'              => $this->sanitize($preApprovalRequest, 'preApprovalCancelUrl'),
            'preApprovalAmountPerPayment'       => $this->sanitizeMoney($preApprovalRequest, 'preApprovalAmountPerPayment'),
            'preApprovalMembershipFee'          => $this->sanitizeMoney($preApprovalRequest, 'preApprovalMembershipFee'),
            'preApprovalTrialPeriodDuration'    => $this->sanitizeNumber($preApprovalRequest, 'preApprovalTrialPeriodDuration'),
            'preApprovalExpirationValue'        => $this->sanitizeNumber($preApprovalRequest, 'preApprovalExpirationValue'),
            'preApprovalExpirationUnit'         => $this->sanitize($preApprovalRequest, 'preApprovalExpirationUnit'),
            'maxUses'                           => $this->sanitizeNumber($preApprovalRequest, 'maxUses'),
        ];

        $this->validatePreApprovalRequest($preApprovalRequest);

        return (string) $this->sendTransaction($preApprovalRequest, $this->url['preApprovalRequest'])->code;
    }

Porem não é possível utilizar o campo reference. Eu modifiquei o metodo e ficou assim:

    /**
     * Define os dados do plano.
     *
     * @param array $preApprovalRequest
     *
     * @return \SimpleXMLElement
     */
    public function sendPreApprovalRequest(array $preApprovalRequest)
    {
        $preApprovalRequest = [
            'email'                             => $this->email,
            'token'                             => $this->token,
            'preApprovalName'                   => $this->sanitize($preApprovalRequest, 'preApprovalName'),
            'preApprovalCharge'                 => $this->sanitize($preApprovalRequest, 'preApprovalCharge'),
            'preApprovalPeriod'                 => $this->sanitize($preApprovalRequest, 'preApprovalPeriod'),
            'preApprovalCancelUrl'              => $this->sanitize($preApprovalRequest, 'preApprovalCancelUrl'),
            'preApprovalAmountPerPayment'       => $this->sanitizeMoney($preApprovalRequest, 'preApprovalAmountPerPayment'),
            'preApprovalMembershipFee'          => $this->sanitizeMoney($preApprovalRequest, 'preApprovalMembershipFee'),
            'preApprovalTrialPeriodDuration'    => $this->sanitizeNumber($preApprovalRequest, 'preApprovalTrialPeriodDuration'),
            'preApprovalExpirationValue'        => $this->sanitizeNumber($preApprovalRequest, 'preApprovalExpirationValue'),
            'preApprovalExpirationUnit'         => $this->sanitize($preApprovalRequest, 'preApprovalExpirationUnit'),
            'maxUses'                           => $this->sanitizeNumber($preApprovalRequest, 'maxUses'),
            'reference'                         => $this->sanitize($preApprovalRequest, 'preApprovalReference')
        ];

        $this->validatePreApprovalRequest($preApprovalRequest);

        return (string) $this->sendTransaction($preApprovalRequest, $this->url['preApprovalRequest'])->code;
    }

Possibilitando utilizar o pacote para criar plano assim:

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function pagseguro()
    {
        $reference = uniqid();

        $response = \Artistas\PagSeguro\PagSeguroRecorrenteFacade::sendPreApprovalRequest([
            'preApprovalReference' => $reference,
            'preApprovalName' => 'Plano ' . $reference, //Nome do plano
            'preApprovalCharge' => 'AUTO', //Tipo de Cobrança
            'preApprovalPeriod' => 'MONTHLY', //Periodicidade do plano
            //'preApprovalCancelURL' => 'https://sistema.spicolibri.com.br', //URL de cancelamento OPCIONAL
            'preApprovalAmountPerPayment' => '1.00', //Valor exato da cobrança
            'preApprovalTrialPeriodDuration' => '28', //Tempo de teste OPCIONAL
            'preApprovalExpirationUnit' => 'MONTHS', //Período em que as cobranças serão realizadas OPCIONAL
        ]);

        dump($response);

        exit;

        return view('recurringsignature::index');
    }

É possível incluir isso ?

Obrigado.

**Comment by felipemarques** [comment]
Segue abaixo imagem para reforçar o que eu quis dizer:

![image](https://user-images.githubusercontent.com/2640656/35710128-f04e41ce-079c-11e8-96ae-01899004a82f.png)

**Comment by fernandobandeira** [comment]
Incluido, como tem um método setReference já que é utilizado em outras requisições, modifiquei o seu PR para utilizar o mesmo, dai a chamada ficou assim:

```php
PagSeguroRecorrente::setReference('referencia opcional') //chamada deste método é opcional
  ->sendPreApprovalRequest([
    'preApprovalName' => 'Nome do Plano', //Nome do plano
    'preApprovalCharge' => 'MANUAL', //Tipo de Cobrança
    'preApprovalPeriod' => 'MONTHLY', //Periodicidade do plano
    'preApprovalCancelURL' => 'http://sitedocliente.com', //URL de cancelamento OPCIONAL
    'preApprovalAmountPerPayment' => '100.00', //Valor exato da cobrança
    'preApprovalMembershipFee' => '150.00', //Taxa de adesão OPCIONAL
    'preApprovalTrialPeriodDuration' => '28', //Tempo de teste OPCIONAL
    'preApprovalExpirationValue' => '10', //Número de cobranças que serão realizadas OPCIONAL
    'preApprovalExpirationUnit' => 'MONTHS', //Período em que as cobranças serão realizadas OPCIONAL
    'maxUses' => '500', //Quantidade máxima de uso do plano OPCIONAL
]);
```

Publicado v1.5.3
