### ISSUE TITLE
Erro ao setar reference

### ISSUE THREAD

**Issue by Georde** [artistas/laravel-pagseguro#92]
$pagseguro = PagSeguro::setReference('id')...

Error:
Non-static method Artistas\PagSeguro\PagSeguro::setReference() should not be called statically

**Comment by Georde** [comment]
Consegui chamando:
$pagseguro = PagSeguroFacade::setReference('id')...

**Comment by fernandobandeira** [comment]
Testei agora com o Laravel 5.6 e nao consegui reproduzir o erro, ele deixa estar normalmente usando o package discovery.
