### ISSUE TITLE
Atualização 1.5.* para 1.6.0 quebrou o pacote

### ISSUE THREAD

**Issue by algoz098** [artistas/laravel-pagseguro#93]
Apos atualizar para a versão 1.6.0 toda rota do pacote retorna que o controller não foi encontrado.

Tentei criar uma instalação do zero do laravel apenas para testar e retorna o mesmo erro. "PagseguroController not found"

**Comment by fernandobandeira** [comment]
Ok, arrumei as rotas, quebrou com o #91 publicado v1.6.1
