### ISSUE TITLE
Dando erro. "In routes.php Line 3 - syntax error, unexpected 'namespace'". 

### ISSUE THREAD

**Issue by ph-woz** [artistas/laravel-pagseguro#95]
Assim que instalei o pacote, deu esse erro.
Estou usando o Laravel 5.4. 
Alguma ideia de como consertar isso?

**Comment by fernandobandeira** [comment]
Tenta utilizar a versao 1.6.2, tinha um recurso sendo utilizado que era suportado apenas na versao 5.5+.

**Comment by fernandobandeira** [comment]
Fechado por inatividade, esta corrigido na 1.6.2
