### ISSUE TITLE
Detalhes sobre o getSenderHash na wiki

### ISSUE THREAD

**Issue by salesfg** [artistas/laravel-pagseguro#97]
Sugiro adicionar a seguinte informação na wiki do projeto (tópico 1.1):

> Atenção: Este método possui algumas dependências e, por isso, recomendamos que o getSenderHash não seja executado no onLoad da página. Você pode executa-lo, por exemplo quando o cliente clicar no botão de conclusão de pagamento.

Motivo: Durante testes realizados, o valor do senderHash era _undefined_ se não seguisse o que a documentação informa.

**Comment by fernandobandeira** [comment]
Ok, ajustei a Wiki.
