### ISSUE TITLE
Erro durante assinatura de plano

### ISSUE THREAD

**Issue by pedrock814** [artistas/laravel-pagseguro#98]
Quando tento fazer a chamada do método de assinatura de plano, conforme a documentação wiki ("PagSeguroRecorrente::setPlan()" ), me é retornado esse erro:

Non-static method Artistas\PagSeguro\PagSeguroRecorrente::setPlan() should not be called statically

De fato o método não é estático, mas alguém poderia me dar uma dica de como contornar esse erro?

**Comment by felipehertzer** [comment]
Olá você precisa utilizar Facade, adicionando la no app as classes de facade do laravel-pagseguro que estão no vendor.
E nos imports você coloca "use PagSeguroRecorrente;"

**Comment by fernandobandeira** [comment]
Como o felipe respondeu acima, não se esqueça de importar a Facade.
